const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Particles,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Acts.LockKeyboard,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Button.Acts.SetFocus
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{CentrarEm: 0},
	{Hero: 0},
	{teclado: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Mouse: 0},
	{Lives: 0},
	{Direcao: 0},
	{bersek: 0},
	{Âncora: 0},
	{Dead: 0},
	{InimigoFire: 0},
	{shield: 0},
	{Limitedireito: 0},
	{LimiteEsquerdo: 0},
	{ProjetorDeSombra: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Botão: 0},
	{Title: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Texto: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Dano: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Gameover: 0},
	{Vidaesqueleto: 0},
	{Sprite8: 0},
	{Invuneravel: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	Hero: class extends self.ISpriteInstance {},
	teclado: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	bersek: class extends self.ISpriteInstance {},
	Lives: class extends self.ITextInstance {},
	Dead: class extends self.IParticlesInstance {},
	InimigoFire: class extends self.ISpriteInstance {},
	shield: class extends self.ISpriteInstance {},
	Limitedireito: class extends self.ISpriteInstance {},
	LimiteEsquerdo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Botão: class extends self.IButtonInstance {},
	Title: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Gameover: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}